### ISSUE TITLE
Proxmox openwrt guest-agent

### ISSUE THREAD

**Issue by docop** [squeekymouse89/proxmoxwrt#1]
Hi Quite great the way you get it deploy.. bit faster than unpacking the .img file.. But, did you get the Guest-agent to be working ? in order to have the ip show and the shutdown of the proxmox ?
thanks in advance

**Comment by squeekymouse89** [comment]
Hi, Thanks for checking out the script ! The script sets the container to unmanaged which means it is not in control of these features. The openwrt filesystem layout is quite different to a regular os so I am not sure how to make proxmox control this element. 

I notice that a container set to DHCP does not show this information anyway so it didn't seem very important. You can always use the Notes section to record details of what has been configured but it will not pass through automatically. 

If you know how to get the guest-agent to work then please let me know. However because its an LCX I dont think it actually uses the guest agent.

**Comment by docop** [comment]
thanks , indeed the dhcp might be be tricky..  But at same time. i wonder to deploy multiple, but i have to do : Stop at each, instead of all doing an 'auto' shutdown by proxmox itself.
thanks again
